CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID LONG NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR not null,
    SURNAME VARCHAR not null,
    AGE INT
);

CREATE TABLE IF NOT EXISTS CONTACTS (
    ID LONG NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_CUSTOMER LONG NOT NULL,
    CONTACT VARCHAR not null,
    TYPE INT not null,
    FOREIGN KEY(ID_CUSTOMER) REFERENCES CUSTOMERS(ID)
);
